version: "3.8"

services:
  postgres:
    container_name: postgresql
    image: postgres:16
    environment:
      POSTGRES_USER: xdpsx
      POSTGRES_PASSWORD: xdpsxpass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: music_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - music-app
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - music-app
    restart: unless-stopped
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_INCOMING_USER=xdpsx
      - MAILDEV_INCOMING_PASS=xdpsxpass
    restart: always
  music-api:
    image: "dranhata/music-api"
    container_name: music-api
    ports:
      - "8081:8080"
    networks:
      - music-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/music_app
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
      - maildev

networks:
  music-app:
    driver: bridge
volumes:
  postgres:
  redis-data:
