version: "3.8"

services:
  postgres:
    container_name: postgresql
    image: postgres:16
    environment:
      POSTGRES_USER: xdpsx
      POSTGRES_PASSWORD: xdpsxpass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: music_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - music-app
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - music-app
    restart: unless-stopped
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_INCOMING_USER=xdpsx
      - MAILDEV_INCOMING_PASS=xdpsxpass
    restart: always

networks:
  music-app:
    driver: bridge
volumes:
  postgres:
  redis-data:
