version: "3.8"

services:
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_INCOMING_USER=xdpsx
      - MAILDEV_INCOMING_PASS=xdpsxpass
    restart: always
