spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
server:
  servlet:
    context-path: /api/${API_VERSION:v1}

aws:
  region: ${AWS_REGION}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucket:
    name: ${AWS_BUCKET_NAME}