server:
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
  cache:
    type: redis
  data:
    redis:
      repositories:
        enabled: false

spring-doc:
  override-with-generic-response: false
  api-docs:
    path: /docs

aws:
  region: ${AWS_REGION}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucket:
    name: ${AWS_BUCKET_NAME}