spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/music_app
    username: xdpsx
    password: xdpsxpass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
  mail:
    host: localhost
    port: 1025
    username: xdpsx
    password: xdpsxpass
    properties:
      mail:
        smtp:
          trust: localhost
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
  data:
    redis:
      host: localhost
      port: 6379
      password:

app:
  mail:
    frontend:
      activation-url: http://localhost:3000/activate-account
  security:
    jwt:
      secret-key: RlNhbjBsM21nVFZHcElGck83dFFLWGlrcFBRRGhyTXhKV240ZmE5
      access-expiration: 86400000 #1 day
      refresh-expiration: 604800000 #7 days