spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      repositories:
        enabled: false

spring-doc:
  override-with-generic-response: false
  api-docs:
    path: /docs
#  default-produces-media-type: "application/json"
#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
#    defaultModelRendering: model
#    requestTimeout: 5000

server:
  servlet:
    context-path: /api/${API_VERSION}

aws:
  region: ${AWS_REGION}
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  bucket:
    name: ${AWS_BUCKET_NAME}